theme: jekyll-theme-minimal
title: 'Genome-Wide Association Studies'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule
  - title: What is Bioinformatics/Genomics?
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/genomics/Genomics_a_perspective_May_2020.pdf

  - heading: Support
  - title: Slack
    url: base/slack
  - title: Zoom
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: CLI
    url: https://ucdavis-bioinformatics-training.github.io/2021-March-Introduction-to-the-Command-Line-for-Bioinformatics/
  - title: R
    url: https://ucdavis-bioinformatics-training.github.io/2021-March-Introduction-to-R-for-Bioinformatics/

  - heading: Data Reduction and Analysis
  - title: Data Reduction
    url: data_reduction/GWAS
  - title: Data Analysis
    url: data_analysis/GWAS

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-July-Genome-Wide-Association-Studies
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
